//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rastreador
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Encomenda = new HashSet<Encomenda>();
        }
    
        public System.Guid Id { get; set; }
        public string Login { get; set; }
        public string Telefone { get; set; }
        public Nullable<int> TemplateId { get; set; }
        public string Token { get; set; }
        public string Modelo { get; set; }
        public string DeviceId { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
    
        public virtual ICollection<Encomenda> Encomenda { get; set; }
        public virtual Template Template { get; set; }
    }
}
